import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Terms — Debrief" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms">
      <p>
        Debrief is a research and critique tool. Output is generated by models
        and web search. It can be wrong, incomplete, or outdated. It is not
        financial, legal, investment, or professional advice. You are
        responsible for how you use it.
      </p>
      <p>
        We may rate-limit or refuse runs that look abusive. You must not use the
        service to attack systems, scrape in violation of third-party terms
        beyond what our providers already allow, or submit unlawful content.
      </p>
      <p>The service is provided as-is, without warranty.</p>
    </LegalPage>
  );
}
