import type { AgentResult, AgentScores, SynthesisResult } from "./types";
import { SCORE_DIMENSIONS } from "./types";
import { stripStructuredBlocks } from "./extractScores";
import type { ResearchResult } from "./research/types";

export type ReportInput = {
  title: string;
  description: string;
  date?: string;
  verdict?: string | null;
  scores?: AgentScores | null;
  agents?: AgentResult[];
  synthesis?: SynthesisResult | null;
  research?: ResearchResult | null;
};

function scoreLine(scores?: AgentScores | null): string {
  if (!scores) return "_not scored_";
  return SCORE_DIMENSIONS.map((dim) => {
    const v = scores[dim];
    return `- ${dim}: ${v === null || v === undefined ? "—" : `${v}/10`}`;
  }).join("\n");
}

/**
 * Builds the full shareable Markdown report. Pure function so it can be
 * unit-tested and reused by clipboard copy, file download, or future APIs.
 */
export function buildReportMarkdown(input: ReportInput): string {
  const parts: string[] = [];

  parts.push(`# Brutal Idea Validator — ${input.title}`);
  parts.push(input.description);
  if (input.date) {
    parts.push(`_Validated ${input.date}_`);
  }

  if (input.verdict || input.scores) {
    let header = "## Verdict\n";
    if (input.verdict) header += `\n**${input.verdict}**\n`;
    if (input.scores) header += `\n### Final scores\n\n${scoreLine(input.scores)}\n`;
    parts.push(header.trim());
  }

  if (input.synthesis?.output) {
    parts.push(`## The Room's Readout\n\n${stripStructuredBlocks(input.synthesis.output)}`);
  }

  for (const agent of input.agents || []) {
    const label = agent.error ? " (failed this run)" : "";
    parts.push(`## Agent: ${agent.agent}${label}\n\n${stripStructuredBlocks(agent.output)}`);
  }

  const research = input.research;
  if (research?.sources?.length) {
    const lines = research.sources
      .map((s) => `- [${s.title}](${s.url}) _(${s.section})_`)
      .join("\n");
    parts.push(`## Live Sources\n\n${lines}`);
  }

  parts.push("---\n_Generated by Brutal Idea Validator. Scores are calibrated harshly: most ideas land 3-6._");
  return parts.join("\n\n");
}

/** Browser helper: downloads the report as a .md file. No-op outside the browser. */
export function downloadReportMarkdown(input: ReportInput): void {
  if (typeof document === "undefined") return;
  const markdown = buildReportMarkdown(input);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  const slug =
    input.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      .slice(0, 60) || "verdict";
  anchor.href = url;
  anchor.download = `${slug}-verdict.md`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
